---
abstract: 'automate the Chrome browser'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires: {}
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize-Chrome
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/Corion/WWW-Mechanize-Chrome.git
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
