---
abstract: 'automate the Chrome browser'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dump: '0'
  Data::Dumper: '0'
  ExtUtils::MakeMaker: 5.52_01
  Image::Info: '0'
  Test::Deep: '0'
  Test::HTTP::LocalServer: '0.71'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  Test::Without::Module: '0'
  Time::HiRes: '0'
  URI: '0'
  URI::file: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize-Chrome
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Loops: '0'
  Carp: '0'
  Exporter: '5'
  File::Basename: '0'
  File::Spec: '0'
  Filter::signatures: '0.16'
  Future: '0.35'
  Future::HTTP: '0.06'
  HTML::Selector::XPath: '0'
  HTTP::Cookies: '0'
  HTTP::Headers: '0'
  HTTP::Response: '0'
  IO::Async: '0'
  IO::Socket::INET: '0'
  IPC::Open3: '0'
  Imager: '0'
  Imager::File::PNG: '0'
  JSON: '0'
  Log::Log4perl: '0'
  MIME::Base64: '0'
  Moo: '2'
  Net::Async::WebSocket::Client: '0.12'
  Object::Import: '0'
  POSIX: '0'
  PerlX::Maybe: '0'
  Scalar::Util: '0'
  Storable: '0'
  Try::Tiny: '0'
  URI: '0'
  URI::file: '0'
  URI::ws: '0'
  WWW::Mechanize::Link: '0'
  perl: '5.010'
resources:
  bugtracker: http://github.com/Corion/WWW-Mechanize-Chrome/issues
  repository: git://github.com/Corion/WWW-Mechanize-Chrome.git
version: '0.70'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
