name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          #- '5.8'
          #- '5.10'
          #- '5.14'
          #- '5.16'
          #- '5.22'
          #- '5.24'
          - '5.26'
          - '5.30'
          #- 'blead'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      #- name: "Install Chrome"
      #  run: |
      #      add-apt-repository ppa:chromium-team/stable
      #      apt-get update
      #      apt-get install chromium-browser libpng-dev
      - name: Install build infrastructure
        run: |
            cpanm --notest --installdeps .
            cpanm --notest AnyEvent AnyEvent::Future AnyEvent::WebSocket::Client
            cpanm --notest Mojolicious Future::Mojo
            cpanm --notest IO::Async Net::Async::WebSocket::Client
      - name: Build
        run: |
            perl Makefile.PL && make
      - name: Run Tests
        run: |
            prove --nocount --jobs 3 -I local/ -bl xt t
