name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@master
      - name: Set up Perl, Chrome
        run: |
          choco install strawberryperl chromium
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: perl -V
        run: perl -V
      - name: Install build infrastructure
        shell: cmd
        run: |
            cpanm --notest --installdeps .
            cpanm --notest AnyEvent AnyEvent::Future AnyEvent::WebSocket::Client
            cpanm --notest Mojolicious Future::Mojo
            cpanm --notest IO::Async Net::Async::WebSocket::Client
      - name: Build
        shell: cmd
        run: |
            perl Makefile.PL
            gmake
      - name: Environment
        shell: cmd
        run: |
            set
      #- name: Chrome location
      #  shell: cmd
      #  run: |
      #      dir /b /s %PROGRAMFILES%\
      #      dir /b /s %ProgramFilesW6432%\
      #      dir /b /s %PROGRAMFILES(x86)%\
      #      dir /b /s %LOCALAPPDATA%\
      - name: Run Tests
        run: prove -I local/ -bl xt t
