name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest
    timeout-minutes: 40

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Set up Perl, Chrome
        run: |
          choco config set cacheLocation "${{ github.workspace }}\choco-cache"
      - name: Set up Perl build environment
        run: |
          # skip installing perl if it is already installed.
          if (!(Test-Path "C:\strawberry\perl\bin")) {
            choco install strawberryperl
          }
          echo @"
          C:\strawberry\c\bin
          C:\strawberry\perl\site\bin
          C:\strawberry\perl\bin
          "@ |
            Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: perl -V
        run: perl -V
      - name: Install build infrastructure
        shell: cmd
        run: |
            call cpanm --notest --installdeps .
            call cpanm --notest AnyEvent AnyEvent::Future AnyEvent::WebSocket::Client
            call cpanm --notest Mojolicious Future::Mojo
            call cpanm --notest IO::Async Net::Async::WebSocket::Client
      - name: Build
        shell: cmd
        run: |
            perl Makefile.PL
            gmake
      - name: Environment
        shell: cmd
        run: |
            set
      #- name: Chrome location
      #  shell: cmd
      #  run: |
      #      dir /b /s %PROGRAMFILES%\
      #      dir /b /s %ProgramFilesW6432%\
      #      dir /b /s %PROGRAMFILES(x86)%\
      #      dir /b /s %LOCALAPPDATA%\
      - name: Run Tests
        run: prove -I local/ -bl xt t
